### ISSUE TITLE
very slow sorting

### ISSUE THREAD

**Issue by jinchang** [muhrin/mincepy_gui#8]
This table should contain roughly 600 entries. When I try to sort it by `converged`, it is stuck in the "Querying" state for a long time (waiting for around 5 minutes now). 

<img width="882" alt="Screen Shot 2020-05-25 at 5 13 14 PM" src="https://user-images.githubusercontent.com/605756/82825223-25438680-9eab-11ea-9fbe-ede169252aa6.png">

**Comment by muhrin** [comment]
This issue appears because you've got 'Display as class' checked.  It's not possible to sort by columns that are based on the instance state of the class.  Only things that are directly variables in the database can be used to sort (i.e. columns visible without checking the 'display as class' checkbox).

I've created an issue against this here: #9.

In this case sorting by 'converged' will be achieved by putting this into the metadata (something  @atygesen is working on) and then to, e.g., add metadata columns to the display.

Closing but feel free to make feature requests if feel more functionality is needed.
